[package]
name = "just-host"
version = "0.0.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.57", default-features = false }
toml-env = { version = "1.2.0", default-features = false }
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18", default-features = false, features = ["ansi", "fmt"] }
