stages:
  - build
  - lint

build-backend:
  stage: build
  image: rust:alpine
  tags:
    - linux
  script:
    - cd backend
    - cargo build

build-prod:
  stage: build
  image: docker:latest
  tags:
    - linux
  services:
    - docker:dind
  script:
    - docker build -f docker/prod/Dockerfile .

format-backend:
  stage: lint
  image: rust:alpine
  tags:
    - linux
  script:
    - cd backend
    - rustup component add rustfmt
    - cargo fmt --check

clippy-backend:
  stage: lint
  image: rust:alpine
  tags:
    - linux
  script:
    - cd backend
    - rustup component add clippy
    - cargo clippy -- -Dwarnings
