stages:
  - build
  - lint

build-backend:
  stage: build
  image: rust:alpine
  tags:
    - linux
  script:
    - cd backend
    - cargo build

build-prod-image:
  stage: build
  image: docker:latest
  tags:
    - linux
  services:
    - docker:dind
  variables:
    CURRENT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    BRANCH_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CURRENT_IMAGE_TAG -t $BRANCH_IMAGE_TAG -f docker/prod/Dockerfile .
    - docker push $CURRENT_IMAGE_TAG
    - docker push $BRANCH_IMAGE_TAG

format-backend:
  stage: lint
  image: rust:alpine
  tags:
    - linux
  script:
    - cd backend
    - rustup component add rustfmt
    - cargo fmt --check

clippy-backend:
  stage: lint
  image: rust:alpine
  tags:
    - linux
  script:
    - cd backend
    - rustup component add clippy
    - cargo clippy -- -Dwarnings
